<?php

use App\Enums\Widget;

return [
    'widget' => Widget::SPACE_CALCULATOR,

    'input-session-key' => 'space-calculator-inputs-uuid',

    'raw-space-standards' => [
        'tight' => [
            0 => 10,
            1 => 2.6,
            2 => 2.52,
        ],
        'average' => [
            0 => 12,
            1 => 2.8,
            2 => 2.9,
        ],
        'spacious' => [
            0 => 18,
            1 => 3.4,
            2 => 3.3,
        ],
    ],

    'circulation_allowances' => [
        'tight' => 19.65,
        'average' => 22.76,
        'spacious' => 25.14,
    ],

    'workstyle-parameters' => [
        \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => [
            'hybrid-working' => [
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::OFFICE->value => 61.92,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::ONE_DAY->value => 55.73,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::TWO_DAYS->value => 50.16,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::THREE_DAYS->value => 40.13,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::FOUR_DAYS->value => 32.1,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::HOME->value => 20.31,
            ],
            'workstations' => [
                'private-offices' => 9.3,
                'use-of-touchdown' => 15.87,
            ],
            'area-adjuster' => 103,
        ],
        \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => [
            'hybrid-working' => [
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::OFFICE->value => 69.62,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::ONE_DAY->value => 62.65,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::TWO_DAYS->value => 56.39,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::THREE_DAYS->value => 45.11,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::FOUR_DAYS->value => 36.09,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::HOME->value => 22.84,
            ],
            'workstations' => [
                'private-offices' => 3.2,
                'use-of-touchdown' => 20.39,
            ],
            'area-adjuster' => 98.4,
        ],
        \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => [
            'hybrid-working' => [
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::OFFICE->value => 77.31,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::ONE_DAY->value => 69.58,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::TWO_DAYS->value => 62.62,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::THREE_DAYS->value => 50.1,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::FOUR_DAYS->value => 40.08,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::HOME->value => 25.36,
            ],
            'workstations' => [
                'private-offices' => 4.6,
                'use-of-touchdown' => 5.38,
            ],
            'area-adjuster' => 102,
        ],
        \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => [
            'hybrid-working' => [
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::OFFICE->value => 81.15,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::ONE_DAY->value => 73.04,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::TWO_DAYS->value => 65.73,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::THREE_DAYS->value => 52.59,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::FOUR_DAYS->value => 42.07,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::HOME->value => 26.62,
            ],
            'workstations' => [
                'private-offices' => 2.1,
                'use-of-touchdown' => 10.43,
            ],
            'area-adjuster' => 100,
        ],
        \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => [
            'hybrid-working' => [
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::OFFICE->value => 81.15,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::ONE_DAY->value => 73.04,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::TWO_DAYS->value => 65.73,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::THREE_DAYS->value => 52.59,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::FOUR_DAYS->value => 42.07,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::HOME->value => 26.62,
            ],
            'workstations' => [
                'private-offices' => 0.3,
                'use-of-touchdown' => 25.69,
            ],
            'area-adjuster' => 97.7,
        ],
        \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => [
            'hybrid-working' => [
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::OFFICE->value => 69.62,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::ONE_DAY->value => 62.55,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::TWO_DAYS->value => 56.39,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::THREE_DAYS->value => 45.11,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::FOUR_DAYS->value => 36.09,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::HOME->value => 22.84,
            ],
            'workstations' => [
                'private-offices' => 23.7,
                'use-of-touchdown' => 5.59,
            ],
            'area-adjuster' => 106.4,
        ],
        \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => [
            'hybrid-working' => [
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::OFFICE->value => 81.15,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::ONE_DAY->value => 73.04,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::TWO_DAYS->value => 65.73,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::THREE_DAYS->value => 52.59,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::FOUR_DAYS->value => 42.07,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::HOME->value => 26.62,
            ],
            'workstations' => [
                'private-offices' => 2.2,
                'use-of-touchdown' => 20.02,
            ],
            'area-adjuster' => 94.1,
        ],
        \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => [
            'hybrid-working' => [
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::OFFICE->value => 75.77,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::ONE_DAY->value => 68.19,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::TWO_DAYS->value => 61.37,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::THREE_DAYS->value => 49.1,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::FOUR_DAYS->value => 39.28,
                \App\Enums\Widgets\SpaceCalculator\HybridWorking::HOME->value => 24.86,
            ],
            'workstations' => [
                'private-offices' => 4.8,
                'use-of-touchdown' => 10.38,
            ],
            'area-adjuster' => 95.7,
        ],
    ],

    'mobility-adjusters' => [
        \App\Enums\Widgets\SpaceCalculator\Mobility::SPECIFIC_DESKS->value => -50,
        \App\Enums\Widgets\SpaceCalculator\Mobility::COMPUTER_MIXTURE->value => -25,
        \App\Enums\Widgets\SpaceCalculator\Mobility::LAPTOPS_DOCKING->value => 0,
        \App\Enums\Widgets\SpaceCalculator\Mobility::LAPTOPS_TOUCHDOWN->value => 25,
        \App\Enums\Widgets\SpaceCalculator\Mobility::LAPTOPS_ANYWHERE->value => 50,
    ],

    'collaboration-adjusters' => [
        \App\Enums\Widgets\SpaceCalculator\Collaboration::INDIVIDUAL_FOCUS->value => -25,
        \App\Enums\Widgets\SpaceCalculator\Collaboration::SOME_MEETINGS->value => -12.5,
        \App\Enums\Widgets\SpaceCalculator\Collaboration::MANY_MEETINGS->value => 0,
        \App\Enums\Widgets\SpaceCalculator\Collaboration::AGILE->value => 12.5,
        \App\Enums\Widgets\SpaceCalculator\Collaboration::ALL_COLLABORATION->value => 25,
    ],

    'asset-parameters' => [
        \App\Enums\Widgets\SpaceCalculator\Asset::PHONE_BOOTH->value => [
            'space-standards' => [
                'tight' => 1.8,
                'average' => 2,
                'spacious' => 2.5,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 1,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => 1,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => null,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 7.12,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 6.95,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 7.03,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 6.11,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 5.07,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 8.3,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 3.35,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 6.26,
            ],
            'use-parameters' => [
                'focus-adjuster' => 'M',
                'threshold-population' => null,
                'maximum-quantity' => null,
                'rounding' => 'U',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::OPEN_BOOTH->value => [
            'space-standards' => [
                'tight' => 1.9,
                'average' => 2.2,
                'spacious' => 3.1,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 1,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => 1,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => null,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 6.35,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 7.3,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 7.32,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 5.14,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 4.82,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 6.7,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 3.31,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 5.05,
            ],
            'use-parameters' => [
                'focus-adjuster' => 'M',
                'threshold-population' => null,
                'maximum-quantity' => null,
                'rounding' => 'U',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::FOCUS_BOOTH->value => [
            'space-standards' => [
                'tight' => 2.8,
                'average' => 3.1,
                'spacious' => 4.1,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 1,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => 1,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => null,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 7.13,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 4.2,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 5.88,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 3.94,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 2.52,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 7.94,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 2.57,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 4.12,
            ],
            'use-parameters' => [
                'focus-adjuster' => 'M',
                'threshold-population' => null,
                'maximum-quantity' => null,
                'rounding' => 'U',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::CHILL_QUIET_SPACE->value => [
            'space-standards' => [
                'tight' => 3,
                'average' => 3.5,
                'spacious' => 4.2,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 1,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => 1,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => null,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 4.56,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 3.85,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 4.45,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 3.27,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 2.49,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 5.05,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 2.02,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 3.33,
            ],
            'use-parameters' => [
                'focus-adjuster' => 'M',
                'threshold-population' => null,
                'maximum-quantity' => null,
                'rounding' => 'U',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::SCRUM_SPACE->value => [
            'space-standards' => [
                'tight' => 16,
                'average' => 18,
                'spacious' => 20,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 8,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => 8,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 0,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 3.72,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 0,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 0,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 12.64,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 0,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 5.52,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 0,
            ],
            'use-parameters' => [
                'focus-adjuster' => 'P',
                'threshold-population' => null,
                'maximum-quantity' => null,
                'rounding' => 'U',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::OPEN_COLLABORATION_TOUCHDOWN->value => [
            'space-standards' => [
                'tight' => 1.2,
                'average' => 1.32,
                'spacious' => 1.452,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 1,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => 1,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 6.28,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 11.05,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 5.03,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 6.64,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 8.22,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 6.03,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 5.93,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 6.93,
            ],
            'use-parameters' => [
                'focus-adjuster' => 'P',
                'threshold-population' => null,
                'maximum-quantity' => null,
                'rounding' => 'U',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::MEETING_BOOTH->value => [
            'space-standards' => [
                'tight' => 6,
                'average' => 7,
                'spacious' => 10,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 4,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => 4,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 15.77,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 9.19,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 3.77,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 12.26,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 6.32,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 21.23,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 9.92,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 8.51,
            ],
            'use-parameters' => [
                'focus-adjuster' => 'P',
                'threshold-population' => null,
                'maximum-quantity' => null,
                'rounding' => 'D',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::WORKSHOP->value => [
            'space-standards' => [
                'tight' => 16,
                'average' => 18,
                'spacious' => 20,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 4,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => 4,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 0,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 5.27,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 0,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 0,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 5.12,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 0,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 0,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 0,
            ],
            'use-parameters' => [
                'focus-adjuster' => 'P',
                'threshold-population' => null,
                'maximum-quantity' => null,
                'rounding' => 'D',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::TWO_PERSON_INTERVIEW_OR_VC_ROOM->value => [
            'space-standards' => [
                'tight' => 3.2,
                'average' => 3.52,
                'spacious' => 3.872,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 2,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => 2,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 13.56,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 6.71,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 13.73,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 7.56,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 6.92,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 14.55,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 7.36,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 6.83,
            ],
            'use-parameters' => [
                'focus-adjuster' => 'P',
                'threshold-population' => null,
                'maximum-quantity' => null,
                'rounding' => 'U',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::FOUR_PERSON_MEETING_ROOM->value => [
            'space-standards' => [
                'tight' => 16.8,
                'average' => 18.48,
                'spacious' => 20.328,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 4,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => 4,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 14.44,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 8.47,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 12.05,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 12.67,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 7.42,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 8.39,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 12.68,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 11.87,
            ],
            'use-parameters' => [
                'focus-adjuster' => 'P',
                'threshold-population' => null,
                'maximum-quantity' => null,
                'rounding' => 'D',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::EIGHT_PERSON_MEETING_ROOM->value => [
            'space-standards' => [
                'tight' => 23.52,
                'average' => 25.872,
                'spacious' => 28.4592,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 8,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => 8,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 13.45,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 16.84,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 22.75,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 13.07,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 16.25,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 15.47,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 12.99,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 11.55,
            ],
            'use-parameters' => [
                'focus-adjuster' => 'P',
                'threshold-population' => null,
                'maximum-quantity' => null,
                'rounding' => 'U',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::TWELVE_PERSON_MEETING_ROOM->value => [
            'space-standards' => [
                'tight' => 30.24,
                'average' => 33.264,
                'spacious' => 36.5904,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 12,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => 12,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 13.34,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 10.12,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 16.14,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 14.71,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 8.43,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 11.01,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 11.66,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 5.88,
            ],
            'use-parameters' => [
                'focus-adjuster' => 'P',
                'threshold-population' => null,
                'maximum-quantity' => null,
                'rounding' => 'D',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::SIXTEEN_PERSON_MEETING_ROOM->value => [
            'space-standards' => [
                'tight' => 36.96,
                'average' => 40.656,
                'spacious' => 44.7216,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 16,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => 16,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 5.73,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 6.3,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 7.86,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 4.9,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 8.83,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 4.19,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 3.89,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 3.99,
            ],
            'use-parameters' => [
                'focus-adjuster' => 'P',
                'threshold-population' => null,
                'maximum-quantity' => null,
                'rounding' => 'D',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::TWENTY_PERSON_MEETING_ROOM->value => [
            'space-standards' => [
                'tight' => 43.68,
                'average' => 48.048,
                'spacious' => 52.8528,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 20,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => 20,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 5.29,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 6.61,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 4.3,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 4.09,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 3.61,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 2.88,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 2.04,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 2.1,
            ],
            'use-parameters' => [
                'focus-adjuster' => 'P',
                'threshold-population' => null,
                'maximum-quantity' => null,
                'rounding' => 'D',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::SERVERY->value => [
            'space-standards' => [
                'tight' => 30,
                'average' => 35,
                'spacious' => 40,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 1,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => null,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 0.42,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 0.26,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 0.47,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 0.33,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 0.28,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 0.55,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 0.52,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 0.41,
            ],
            'use-parameters' => [
                'focus-adjuster' => null,
                'threshold-population' => 300,
                'maximum-quantity' => 2,
                'rounding' => 'D',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::CATERING_KITCHEN_AND_STORES->value => [
            'space-standards' => [
                'tight' => 25,
                'average' => 30,
                'spacious' => 35,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 1,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => null,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 0.34,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 0.18,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 0.39,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 0.25,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 0.21,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 0.48,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 0.52,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 0.4,
            ],
            'use-parameters' => [
                'focus-adjuster' => null,
                'threshold-population' => 400,
                'maximum-quantity' => 2,
                'rounding' => 'D',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::CANTEEN_SEATING_SPACE->value => [
            'space-standards' => [
                'tight' => 1.2,
                'average' => 1.5,
                'spacious' => 1.8,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 1,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => 1,
                'recreation' => null,
                'team-meeting' => null,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 15.4,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 17.2,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 20.1,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 18,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 16.2,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 19.7,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 20.5,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 16.4,
            ],
            'use-parameters' => [
                'focus-adjuster' => null,
                'threshold-population' => 300,
                'maximum-quantity' => null,
                'rounding' => 'D',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::TEAPOINT->value => [
            'space-standards' => [
                'tight' => 12,
                'average' => 15,
                'spacious' => 20,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 1,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => null,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 0.67,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 0.67,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 0.67,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 0.67,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 0.67,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 0.67,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 0.67,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 0.67,
            ],
            'use-parameters' => [
                'focus-adjuster' => null,
                'threshold-population' => null,
                'maximum-quantity' => null,
                'rounding' => 'U',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::KITCHEN_AND_BAR->value => [
            'space-standards' => [
                'tight' => 25,
                'average' => 30,
                'spacious' => 35,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 1,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => null,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 0.5,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 0.5,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 0.5,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 0.5,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 0.5,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 0.5,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 0.5,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 0.5,
            ],
            'use-parameters' => [
                'focus-adjuster' => null,
                'threshold-population' => 100,
                'maximum-quantity' => null,
                'rounding' => 'D',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::GAMES_AREA->value => [
            'space-standards' => [
                'tight' => 24,
                'average' => 30,
                'spacious' => 35,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 4,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => 4,
                'team-meeting' => null,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 1,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 2.5,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 0,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 2,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 3.2,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 0,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 1.6,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 0.8,
            ],
            'use-parameters' => [
                'focus-adjuster' => null,
                'threshold-population' => 200,
                'maximum-quantity' => 2,
                'rounding' => 'D',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::GAMES_ROOM->value => [
            'space-standards' => [
                'tight' => 12,
                'average' => 15,
                'spacious' => 20,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 6,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => 6,
                'team-meeting' => null,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 1.2,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 3.6,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 0.5,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 2,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 4.7,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 0,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 2.7,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 0,
            ],
            'use-parameters' => [
                'focus-adjuster' => null,
                'threshold-population' => 150,
                'maximum-quantity' => 2,
                'rounding' => 'D',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::BREAKOUT_SEATS_OF_VARIOUS_TYPES->value => [
            'space-standards' => [
                'tight' => 1.2,
                'average' => 1.5,
                'spacious' => 1.8,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 1,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => 1,
                'recreation' => null,
                'team-meeting' => null,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 11.1,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 12.2,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 8.2,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 10,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 9.6,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 8.4,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 10.5,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 8,
            ],
            'use-parameters' => [
                'focus-adjuster' => 'P',
                'threshold-population' => null,
                'maximum-quantity' => null,
                'rounding' => 'U',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::RECEPTION_DESK_POSITIONS->value => [
            'space-standards' => [
                'tight' => 12,
                'average' => 16,
                'spacious' => 20,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 1,
                'long-dwell-workstation' => 1,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => null,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 0.96,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 0.72,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 1.12,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 0.64,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 0.96,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 1.36,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 0.48,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 0.48,
            ],
            'use-parameters' => [
                'focus-adjuster' => null,
                'threshold-population' => 50,
                'maximum-quantity' => 4,
                'rounding' => 'U',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::RECEPTION_WAITING_AREA_SEATS->value => [
            'space-standards' => [
                'tight' => 2.7,
                'average' => 3,
                'spacious' => 3.3,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 1,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => null,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 5.25,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 3.33,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 6.02,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 4.35,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 3.46,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 7.94,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 2.43,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 3.07,
            ],
            'use-parameters' => [
                'focus-adjuster' => null,
                'threshold-population' => 10,
                'maximum-quantity' => 20,
                'rounding' => 'U',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::RECEPTION_STORAGE->value => [
            'space-standards' => [
                'tight' => 7.2,
                'average' => 8,
                'spacious' => 8.8,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 1,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => null,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 0.24,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 0.16,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 0.32,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 0.16,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 0.16,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 0.32,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 0.08,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 0.08,
            ],
            'use-parameters' => [
                'focus-adjuster' => null,
                'threshold-population' => 25,
                'maximum-quantity' => '3',
                'rounding' => 'U',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::FURNITURE_STORE->value => [
            'space-standards' => [
                'tight' => 10.8,
                'average' => 12,
                'spacious' => 13.2,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 1,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => null,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 0.23,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 0.15,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 0.31,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 0.15,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 0.15,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 0.31,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 0.08,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 0.08,
            ],
            'use-parameters' => [
                'focus-adjuster' => null,
                'threshold-population' => 150,
                'maximum-quantity' => 1,
                'rounding' => 'D',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::FRONT_OF_HOUSE_KITCHEN->value => [
            'space-standards' => [
                'tight' => 18,
                'average' => 20,
                'spacious' => 22,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 1,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => null,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 0.12,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 0.08,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 0.16,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 0.08,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 0.08,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 0.16,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 0.04,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 0.04,
            ],
            'use-parameters' => [
                'focus-adjuster' => null,
                'threshold-population' => 200,
                'maximum-quantity' => 1,
                'rounding' => 'D',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::TWO_PERSON_INTERVIEW_ROOM->value => [
            'space-standards' => [
                'tight' => 3.8016,
                'average' => 4.224,
                'spacious' => 4.6464,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 2,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => null,
                'front-of-house-meeting' => 2,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 2.88,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 1.92,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 2.56,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 1.2,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 3.28,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 4.96,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 2.41290322580645,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 2.51797323135755,
            ],
            'use-parameters' => [
                'focus-adjuster' => null,
                'threshold-population' => null,
                'maximum-quantity' => 4,
                'rounding' => 'U',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::FOUR_PERSON_CONFERENCE_ROOM->value => [
            'space-standards' => [
                'tight' => 19.9584,
                'average' => 22.176,
                'spacious' => 24.3936,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 4,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => null,
                'front-of-house-meeting' => 4,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 3.44,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 3.22567901234568,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 4.96,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 3.6,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 3.5165811965812,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 9.95000928505107,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 4.15555555555556,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 2.96,
            ],
            'use-parameters' => [
                'focus-adjuster' => null,
                'threshold-population' => null,
                'maximum-quantity' => 20,
                'rounding' => 'D',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::EIGHT_PERSON_CONFERENCE_ROOM->value => [
            'space-standards' => [
                'tight' => 27.94176,
                'average' => 31.0464,
                'spacious' => 34.15104,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 8,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => null,
                'front-of-house-meeting' => 8,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 9.14804862444018,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 6.41202047576031,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 16.721152,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 5.38613861386139,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 7.69846153846154,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 18.3453296193129,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 4.25609318996416,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 4.26118546845124,
            ],
            'use-parameters' => [
                'focus-adjuster' => null,
                'threshold-population' => null,
                'maximum-quantity' => 20,
                'rounding' => 'U',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::TWELVE_PERSON_CONFERENCE_ROOM->value => [
            'space-standards' => [
                'tight' => 35.92512,
                'average' => 39.9168,
                'spacious' => 43.90848,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 12,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => null,
                'front-of-house-meeting' => 12,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 9.07306461932182,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 3.8550797952424,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 11.866624,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 6.05940594059406,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 3.99179487179487,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 13.0593871866295,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 3.82043010752688,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 2.16933078393881,
            ],
            'use-parameters' => [
                'focus-adjuster' => null,
                'threshold-population' => null,
                'maximum-quantity' => 20,
                'rounding' => 'D',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::SIXTEEN_PERSON_CONFERENCE_ROOM->value => [
            'space-standards' => [
                'tight' => 43.90848,
                'average' => 48.7872,
                'spacious' => 53.66592,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 16,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => null,
                'front-of-house-meeting' => 16,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 3.89916826615483,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 2.39959048479374,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 5.7792,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 2.01980198019802,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 4.18188034188034,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 4.97500464252553,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 1.27347670250896,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 1.47204588910134,
            ],
            'use-parameters' => [
                'focus-adjuster' => null,
                'threshold-population' => null,
                'maximum-quantity' => 20,
                'rounding' => 'D',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::TWENTY_PERSON_CONFERENCE_ROOM->value => [
            'space-standards' => [
                'tight' => 51.89184,
                'average' => 57.6576,
                'spacious' => 63.42336,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 20,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => null,
                'front-of-house-meeting' => 20,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 3.59923224568138,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 2.51760313158687,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 3.159296,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 1.68316831683168,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 1.71076923076923,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 3.4203156917363,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 0.670250896057348,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 0.774760994263862,
            ],
            'use-parameters' => [
                'focus-adjuster' => null,
                'threshold-population' => null,
                'maximum-quantity' => 20,
                'rounding' => 'D',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::FIFTY_PERSON_CONFERENCE_ROOM->value => [
            'space-standards' => [
                'tight' => 75,
                'average' => 88,
                'spacious' => 92,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 50,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => null,
                'front-of-house-meeting' => 50,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 10,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 8.32,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 12.88,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 0,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 9.12,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 28.48,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 0,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 0,
            ],
            'use-parameters' => [
                'focus-adjuster' => null,
                'threshold-population' => 250,
                'maximum-quantity' => 2,
                'rounding' => 'D',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::MAIN_EQUIPMENT_ROOM->value => [
            'space-standards' => [
                'tight' => 21,
                'average' => 23,
                'spacious' => 25,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 1,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => null,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 0.36,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 0.31,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 0.34,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 0.33,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 0.33,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 0.35,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 0.31,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 0.31,
            ],
            'use-parameters' => [
                'focus-adjuster' => null,
                'threshold-population' => null,
                'maximum-quantity' => 1,
                'rounding' => 'D',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::COMMS_ROOM_OR_SER->value => [
            'space-standards' => [
                'tight' => 9,
                'average' => 10,
                'spacious' => 11,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 1,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => null,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 0.51,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 0.54,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 0.51,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 0.5,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 0.52,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 0.49,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 0.48,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 0.45,
            ],
            'use-parameters' => [
                'focus-adjuster' => null,
                'threshold-population' => null,
                'maximum-quantity' => null,
                'rounding' => 'U',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::IT_BUILD_ROOM->value => [
            'space-standards' => [
                'tight' => 9,
                'average' => 12,
                'spacious' => 14,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 1,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => null,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 0.32,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 0.33,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 0.3,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 0.33,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 0.35,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 0.31,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 0.31,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 0.35,
            ],
            'use-parameters' => [
                'focus-adjuster' => null,
                'threshold-population' => null,
                'maximum-quantity' => 2,
                'rounding' => 'D',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::PRINT_AND_COPY_AREA->value => [
            'space-standards' => [
                'tight' => 5,
                'average' => 6,
                'spacious' => 7,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 1,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => null,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 1.01,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 0.91,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 1.01,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 1,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 1.04,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 1,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 1.04,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 1.1,
            ],
            'use-parameters' => [
                'focus-adjuster' => null,
                'threshold-population' => null,
                'maximum-quantity' => null,
                'rounding' => 'U',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::STATIONARY_STORE->value => [
            'space-standards' => [
                'tight' => 7,
                'average' => 8,
                'spacious' => 9,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 1,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => null,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 0.54,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 0.49,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 0.51,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 0.5,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 0.53,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 0.51,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 0.52,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 0.48,
            ],
            'use-parameters' => [
                'focus-adjuster' => null,
                'threshold-population' => null,
                'maximum-quantity' => null,
                'rounding' => 'D',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::FACILITIES_STORE->value => [
            'space-standards' => [
                'tight' => 8,
                'average' => 9,
                'spacious' => 10,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 1,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => null,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 0.47,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 0.52,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 0.46,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 0.5,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 0.46,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 0.54,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 0.5,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 0.48,
            ],
            'use-parameters' => [
                'focus-adjuster' => null,
                'threshold-population' => null,
                'maximum-quantity' => null,
                'rounding' => 'U',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::COAT_STORAGE->value => [
            'space-standards' => [
                'tight' => 0.6,
                'average' => 0.7,
                'spacious' => 0.8,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 10,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => null,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 25.55,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 26.05,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 22.65,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 25,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 25.35,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 25.15,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 24.4,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 23.7,
            ],
            'use-parameters' => [
                'focus-adjuster' => null,
                'threshold-population' => null,
                'maximum-quantity' => null,
                'rounding' => 'U',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::CLEANERS_CUPBOARD->value => [
            'space-standards' => [
                'tight' => 5,
                'average' => 6,
                'spacious' => 7,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 1,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => null,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 0.48,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 0.53,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 0.54,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 0.5,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 0.5,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 0.52,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 0.52,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 0.47,
            ],
            'use-parameters' => [
                'focus-adjuster' => null,
                'threshold-population' => null,
                'maximum-quantity' => null,
                'rounding' => 'U',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::PRAYER_ROOM->value => [
            'space-standards' => [
                'tight' => 10,
                'average' => 11,
                'spacious' => 12,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 1,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => null,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 0.64,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 0.66,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 0.65,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 0.67,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 0.62,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 0.67,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 0.73,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 0.65,
            ],
            'use-parameters' => [
                'focus-adjuster' => null,
                'threshold-population' => null,
                'maximum-quantity' => 4,
                'rounding' => 'D',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::FOUR_HIGH_LOCKERS->value => [
            'space-standards' => [
                'tight' => 0.25,
                'average' => 0.25,
                'spacious' => 0.25,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 4,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => null,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 26,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 24.93,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 27.37,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 25,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 25.73,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 26.45,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 25.95,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 23.89,
            ],
            'use-parameters' => [
                'focus-adjuster' => null,
                'threshold-population' => null,
                'maximum-quantity' => null,
                'rounding' => 'U',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::GYM->value => [
            'space-standards' => [
                'tight' => 25,
                'average' => 30,
                'spacious' => 35,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 6,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => 6,
                'team-meeting' => null,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 2.25,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 3.08,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 3.38,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 3,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 2.7,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 2.48,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 1.88,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 0.75,
            ],
            'use-parameters' => [
                'focus-adjuster' => null,
                'threshold-population' => 300,
                'maximum-quantity' => 1,
                'rounding' => 'D',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::STUDIO->value => [
            'space-standards' => [
                'tight' => 20,
                'average' => 25,
                'spacious' => 30,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 6,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => 6,
                'team-meeting' => null,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 2.48,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 3.9,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 3.45,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 2.78,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 2.03,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 2.1,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 1.13,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 0,
            ],
            'use-parameters' => [
                'focus-adjuster' => null,
                'threshold-population' => 500,
                'maximum-quantity' => 1,
                'rounding' => 'D',
            ]
        ],
        \App\Enums\Widgets\SpaceCalculator\Asset::SHOWERS_AND_CHANGING_AREA->value => [
            'space-standards' => [
                'tight' => 16,
                'average' => 18,
                'spacious' => 20,
            ],
            'capacity-and-multiples' => [
                'unit-multiple' => 1,
                'long-dwell-workstation' => null,
                'short-dwell-workstation' => null,
                'focus-space' => null,
                'breakout' => null,
                'recreation' => null,
                'team-meeting' => null,
                'front-of-house-meeting' => null,
            ],
            'workstyle-parameters' => [
                \App\Enums\Widgets\SpaceCalculator\Workstyle::SERVICE_DELIVERY->value => 1,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::CREATIVE->value => 1,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::FINANCIAL->value => 1,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::GENERAL->value => 1,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::TECHNOLOGY->value => 1,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::LAW->value => 1,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PROCESS_DRIVEN->value => 1,
                \App\Enums\Widgets\SpaceCalculator\Workstyle::PUBLIC_SECTOR->value => 1,
            ],
            'use-parameters' => [
                'focus-adjuster' => null,
                'threshold-population' => 450,
                'maximum-quantity' => 1,
                'rounding' => 'D',
            ]
        ],
    ],

];
