name: "Pipeline: Test"

on:
  push:
    branches:
      - 'test'
  workflow_dispatch:

jobs:
  build-assets:
    uses: ./.github/workflows/build-assets.yml

#  deployer-test-deploy:
#    needs: [build-assets]
#    uses: ./.github/workflows/deployer-test-deploy.yml
#    secrets: inherit
