name: Build Assets

on:
    workflow_call:

jobs:
    build-assets:
        name: Build Assets

        runs-on: ubuntu-22.04

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Install NPM dependencies
                run: npm ci

            -   name: Vite build
                run: npm run build

            -   name: Upload built assets
                uses: actions/upload-artifact@v3
                with:
                    name: assets-${{ github.sha }}
                    path: public/build
                    retention-days: 7
